version: '2'
services:
  # Node configuration
  node:
    build:
      context: ./docker/node
    volumes:
      - ./:/app
    command: npm run runserver:hmr
    ports:
      - "8080:8080"
      - "9876:9876"
