name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version': "16"

    - name: Install dependencies
      run: npm install

    - name: Build library
      run: npm run build

    - name: Create build artifact
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: dist
