name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["14"]
        angular: ["~10.0.0", "~10.1.0",  "~10.2.0", "~11.0.0", "~11.1.0", "~11.2.0" ,"~12.0.0", "~12.1.0", "~12.2.0"]
        typescript: ["~3.9.0","~4.0.0", "~4.1.0", "~4.2.0", "~4.3.0"]

        exclude:
          - angular: "~10.0.0"
            typescript: "~4.0.0"
          - angular: "~10.0.0"
            typescript: "~4.1.0"
          - angular: "~10.0.0"
            typescript: "~4.2.0"
          - angular: "~10.0.0"
            typescript: "~4.3.0"

          - angular: "~10.1.0"
            typescript: "~4.1.0"
          - angular: "~10.1.0"
            typescript: "~4.2.0"
          - angular: "~10.1.0"
            typescript: "~4.3.0"

          - angular: "~10.2.0"
            typescript: "~4.1.0"
          - angular: "~10.2.0"
            typescript: "~4.2.0"
          - angular: "~10.2.0"
            typescript: "~4.3.0"
          
          - angular: "~11.0.0"
            typescript: "~3.9.0"
          - angular: "~11.0.0"
            typescript: "~4.1.0"
          - angular: "~11.0.0"
            typescript: "~4.2.0"
          - angular: "~11.0.0"
            typescript: "~4.3.0"

          - angular: "~11.1.0"
            typescript: "~3.9.0"
          - angular: "~11.1.0"
            typescript: "~4.1.0"
          - angular: "~11.1.0"
            typescript: "~4.2.0"
          - angular: "~11.1.0"
            typescript: "~4.3.0"

          - angular: "~11.2.0"
            typescript: "~3.9.0"
          - angular: "~11.2.0"
            typescript: "~4.1.0"
          - angular: "~11.2.0"
            typescript: "~4.2.0"
          - angular: "~11.2.0"
            typescript: "~4.3.0"

          
          - angular: "~12.0.0"
            typescript: "~3.9.0"
          - angular: "~12.0.0"
            typescript: "~4.0.0"
          - angular: "~12.0.0"
            typescript: "~4.1.0"
          - angular: "~12.0.0"
            typescript: "~4.3.0"

          - angular: "~12.1.0"
            typescript: "~3.9.0"
          - angular: "~12.1.0"
            typescript: "~4.0.0"
          - angular: "~12.1.0"
            typescript: "~4.1.0"

          - angular: "~12.2.0"
            typescript: "~3.9.0"
          - angular: "~12.2.0"
            typescript: "~4.0.0"
          - angular: "~12.2.0"
            typescript: "~4.1.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm

    - name: Install dependencies
      run: npm install

    - run: npm install typescript@${{ matrix.typescript }}
    - run: npm install @angular/common@${{ matrix.angular }}
    - run: npm install @angular/compiler@${{ matrix.angular }}
    - run: npm install @angular/compiler-cli@${{ matrix.angular }}
    - run: npm install @angular/core@${{ matrix.angular }}
    - run: npm install @angular/platform-browser@${{ matrix.angular }}

    - name: Run tests
      run: npm run test-ci

    - name: Build library
      run: npm run build
