name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 13.x, 14.x]
        angular: ["~8.0.0", "~8.1.0", "~8.2.0", "~9.0.0", "~9.1.0", "~10.0.0", "~10.1.0"]
        typescript: ["~3.4.0", "~3.5.0", "~3.6.0", "~3.7.0", "~3.8.0", "~3.9.0","~4.0.0"]

        exclude:
          - angular: "~8.0.0"
            typescript: "~4.0.0"
          - angular: "~8.0.0"
            typescript: "~3.9.0"
          - angular: "~8.0.0"
            typescript: "~3.8.0"
          - angular: "~8.0.0"
            typescript: "~3.7.0"
          - angular: "~8.0.0"
            typescript: "~3.6.0"
          - angular: "~8.0.0"
            typescript: "~3.5.0"

          - angular: "~8.1.0"
            typescript: "~4.0.0"
          - angular: "~8.1.0"
            typescript: "~3.9.0"
          - angular: "~8.1.0"
            typescript: "~3.8.0"
          - angular: "~8.1.0"
            typescript: "~3.7.0"
          - angular: "~8.1.0"
            typescript: "~3.6.0"
          - angular: "~8.1.0"
            typescript: "~3.5.0"

          - angular: "~8.2.0"
            typescript: "~4.0.0"
          - angular: "~8.2.0"
            typescript: "~3.9.0"
          - angular: "~8.2.0"
            typescript: "~3.8.0"
          - angular: "~8.2.0"
            typescript: "~3.7.0"
          - angular: "~8.2.0"
            typescript: "~3.6.0"

          - angular: "~9.0.0"
            typescript: "~4.0.0"
          - angular: "~9.0.0"
            typescript: "~3.9.0"
          - angular: "~9.0.0"
            typescript: "~3.8.0"
          - angular: "~9.0.0"
            typescript: "~3.4.0"
          - angular: "~9.0.0"
            typescript: "~3.5.0"

          - angular: "~9.1.0"
            typescript: "~4.0.0"
          - angular: "~9.1.0"
            typescript: "~3.9.0"
          - angular: "~9.1.0"
            typescript: "~3.4.0"
          - angular: "~9.1.0"
            typescript: "~3.5.0"

          - angular: "~10.0.0"
            typescript: "~4.0.0"
          - angular: "~10.0.0"
            typescript: "~3.4.0"
          - angular: "~10.0.0"
            typescript: "~3.5.0"
          - angular: "~10.0.0"
            typescript: "~3.6.0"
          - angular: "~10.0.0"
            typescript: "~3.7.0"
          - angular: "~10.0.0"
            typescript: "~3.8.0"

          - angular: "~10.1.0"
            typescript: "~3.4.0"
          - angular: "~10.1.0"
            typescript: "~3.5.0"
          - angular: "~10.1.0"
            typescript: "~3.6.0"
          - angular: "~10.1.0"
            typescript: "~3.7.0"
          - angular: "~10.1.0"
            typescript: "~3.8.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - run: npm install typescript@${{ matrix.typescript }}
    - run: npm install @angular/common@${{ matrix.angular }}
    - run: npm install @angular/compiler@${{ matrix.angular }}
    - run: npm install @angular/compiler-cli@${{ matrix.angular }}
    - run: npm install @angular/core@${{ matrix.angular }}
    - run: npm install @angular/platform-browser@${{ matrix.angular }}

    - name: Run tests
      run: npm run test-ci

    - name: Build library
      run: npm run build
